version: '3'
services:
  # mysql
  mysql:
    image: 'mysql:5.7.24'
    container_name: 'house-mysql'
    command: --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
    # TODO: env 처리해야함.
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_DATABASE: 'test'
  # backend
  # TODO: Dockerfile 연동해야함.
  backend:
    image: 'node:12.13-alpine'
    container_name: 'house-node'
    ports:
      - '3000:3000'
