version: '3'
services:
  # mysql
  database:
    # TODO: 8.0은 NoSQL 기능 지원, auto increment 유지, 새로운 인덱스 기능 3개 추가 되었다고 한다.
    # 검토후에 변경하기
    image: 'mysql:5.7.31'
    container_name: 'house-database'
    command: --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
    # TODO: env 처리해야함.
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_DATABASE: 'test'
    networks:
      - backend
  # app
  app:
    build: ./app
    # yml에서 scale 옵션은 3에서 제거되었다.
    # scale에서는 container_name을 사용하지 못한다.
    # container_name: 'house-app'
    environment:
      TYPEORM_CONNECTION: mysql
      TYPEORM_HOST: house-database
      TYPEORM_USERNAME: test
      TYPEORM_PASSWORD: test
      TYPEORM_DATABASE: test
      TYPEORM_PORT: 3306
      TYPEORM_SYNCHRONIZE: 1
      TYPEORM_ENTITIES: dist/**/*.entity.ts,dist/**/*.entity.js
      # TYPEORM_LOGGING: true
    ports:
      - 3000
    depends_on:
      - database
    networks:
      - backend

  # nginx
  nginx:
    container_name: 'house-nginx'
    build: ./nginx
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
    ports:
      - '8000:8000'
    depends_on:
      - database
      - app
    networks:
      - backend

  # filebeat
  filebeat:
    container_name: 'house-filebeat'
    build: ./filebeat
    entrypoint: 'filebeat -e -strict.perms=false'
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./nginx/log:/var/log/nginx
    networks:
      - backend
      # NOTE: elk network 확인
      - elk-find-my-best-home_elk
    depends_on:
      - nginx

networks:
  backend:
    driver: bridge
  elk-find-my-best-home_elk:
    external: true
