FROM mysql:5.7.31

ENV MYSQL_ROOT_PASSWORD=admin
ENV MYSQL_USER=test
ENV MYSQL_PASSWORD=test
ENV MYSQL_DATABASE=test

EXPOSE 3306

CMD ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
